### PR TITLE
[WIP] refactor: detector architecture, split to own files

### PR DESCRIPTION
**Pull request by erikarenhill**
To avoid all these if-else cases to check for which detector to use I propose that we split up those to own detector objects and use some kind of factory to use them. This way it would be really easy to add another 4:th detector in the future instead of putting in more logic.

I think it'll be easier to maintain if the architecture goes this direction

This is just an initial proposal/commit for how the recognize feature could look like, and before refactoring further please add some feedback/thoughts.

The interesting part is really the difference in recognize.util.js where we just replace the detector-switching logic and actual axios-calls with a one-liner

What do you think about it @jakowenko ?

### CODE REVIEW

**Comment by jakowenko** [comment]
I really like the direction you're going with this. I've been working on some local changes to include object detection support too, but would like to help you work on this detector refactor before I add in any more changes.

**Comment by erikarenhill** [comment]
npm-watch is actually using nodemon under the hood, I just like the way watch is configured in package.json, but go with nodemon if you prefer that :)

Keeping nodemon local/global keeps makes one less dependency for the project though

I didn't have the time to go through other parts of the application yet, but I also started looking into saving images with face < CONFIDENCE to an unmatched directory.

If you'd like to we can merge this into your beta-branch and then you can continue from there? I suspect you put more time into this than I am so if you'd like to prioritize it maybe its better you take over this. Still want to be able to contribute from time to time

**Comment by jakowenko** [comment]
Good to know about npm-watch. I noticed it was using nodemon when I was testing it out, just don't have a lot of experience with it, so I will look into it a bit more.

Merging into beta sounds good to me! Thanks for updating that. I'll try to get this merged in this evening.

**Comment by jakowenko** [comment]
I'll take a look at what would be involved to save unmatched faces to an unmatched directory too. That makes perfect sense and would make it easier to retrain the models with these faces if no match is found.

**Comment by erikarenhill** [comment]
> I'll take a look at what would be involved to save unmatched faces to an unmatched directory too. That makes perfect sense and would make it easier to retrain the models with these faces if no match is found.

I have a branch here might be useful, not sure if this is the best place to put the code though.  https://github.com/erikarenhill/double-take/tree/feat/save_unmatched_for_training

**Comment by jakowenko** [comment]
Feel free to open another WIP PR if you'd like, or I can just copy over the changes directly if that's easier for you. Looks like you only touched that one file. I agree with your TODO's in it. I wanted to move the logic of saving the files outside of the polling function, but this should suffice for now. I can work on refactoring that logic after.

**Comment by jakowenko** [comment]
Do you think all faces that aren't matched should be saved? Compreface seems to always return one of the names it was trained with even if there's a really low confidence score so the logic you had would work for that detector. But, Facebox and DeepStack will return a boolean if a face is found but no match is found from the model.

I think saving all non matched faces is ideal. I will need to update normalize function to take in all the results and then filter out the unmatched ones for saving. Right now any faces that aren't matched from Facebox or DeepStack are removed from the current array.

I'll try to take a closer look at this logic tomorrow.

**Pull request merged**
