### PR TITLE
FEAT: Support Frigate sub labels

### PR DESCRIPTION
**Pull request by NickM-27**
I added a [PR over at Frigate](https://github.com/blakeblackshear/frigate/pull/2949) to support setting sub labels. This will allow double-take to update the `Person` label to be `Person: Nick` (for example). 

This is a WIP and I am still trying to figure out how to add this to double-take as I am new to working with it. @jakowenko if you have any recommendations on where to insert this logic that would be much appreciated.

### CODE REVIEW

**Comment by jakowenko** [comment]
Hey @NickM-27, cool feature. Once this gets merged into Frigate or there is a beta build for me to work off, I should be able to update Double Take to include it.

**Comment by NickM-27** [comment]
@jakowenko Thanks! That would be good, I think it may still be a little bit before the first `0.11.0` beta but will see. Would you like me to close this PR or leave open as a reminder?

**Comment by jakowenko** [comment]
I'll probably make a feature issue request and track it that way. But you can keep it open for now and I will close once I put in the feature.

**Comment by NickM-27** [comment]
@jakowenko Just a heads up my PR for this feature over at frigate was merged into the release branch, still not sure when a beta will be sent out 👍

**Comment by jakowenko** [comment]
> @jakowenko Frigate beta with this feature is live: [blakeblackshear/frigate#3221](https://github.com/blakeblackshear/frigate/discussions/3221)

Thank you. Getting back into working on this again and I'll try to prioritize this feature.

**Comment by jakowenko** [comment]
@NickM-27 this is implemented now in v1.9.0. Let me know if you run into any issues. The Docker image is building now and should be done in about an hour.

Thank you for this request. It seems like it will be very handy to be able to reference the labels in Frigate.

**Comment by NickM-27** [comment]
@jakowenko thank you for implementing it quickly! I'll test it soon and let you know.

**Comment by jakowenko** [comment]
> @jakowenko Everything looks good so far. Hopefully I will have a chance to test two people walking past a camera at the same time, but that is the last case that I haven't been able to test

Great to hear! If two people are detected, I concat the names into one. So the sublabel should be `Person 1, Person 2`

**Comment by NickM-27** [comment]
> If two people are detected, I concat the names into one. So the sublabel should be Person 1, Person 2

Oh cool, that will be awesome!

**Pull request closed without merging**
