### PR TITLE
Fix det_prob_threshold in compreface detector test

### PR DESCRIPTION
**Pull request by bigbangus**
Changed det_prob_threshold from 0 to 0.8 when testing the compreface detector to address issue with compreface custom-builds.

### CODE REVIEW

**Comment by juan11perez** [comment]
I have very similar hardware (GTX 1050Ti, Ryzen 9 3900X w/64MB RAM) with unraid 6.9.2 and experienced exactly the same issue.

I have modified the double-take docker per above referred pull request and it now works with mobilenet-gpu.

Thank you

**Comment by wills106** [comment]
Just want to confirm this issue has resolved my problem as well running compreface:0.6.1-arcface-r100-gpu on a GTX1650

**Comment by bigbangus** [comment]
@jakowenko do you think it would be possible to roll this into the next release?

**Comment by steppel** [comment]
> Changed det_prob_threshold from 0 to 0.8 when testing the compreface detector to address issue with compreface custom-builds.

@bigbangus I did spin up a container with the change you suggest. I still have the same problem. You sure thats the reason?

`192.168.1.xxx - - [28/Mar/2022:12:45:57 -0700] "POST /api/v1/recognition/recognize?face_plugins=undefined&det_prob_threshold=0.8 HTTP/1.1" 499 0 "-" "axios/0.24.0"`

**Comment by juan11perez** [comment]
@jakowenko 
Can you please consider this request for next release? the proposed solution resolves the problem and I noticed your latest version is unchanged.
Thank you

**Comment by bigbangus** [comment]
So far it's been very stable with compreface gpu as long as I avoid the /config page, but yes would be great to have this change considered thank you!

**Comment by jakowenko** [comment]
Sorry for the delay in this. This is implemented now in v1.9.0. Let me know if you run into any issues. The Docker image is building now and should be done in about an hour.

**Comment by juan11perez** [comment]
@jakowenko thank you for your prompt reply.
It's now working well with the single 'exadel/compreface:0.6.1-mobilenet-gpu' docker.

**Comment by bigbangus** [comment]
@jakowenko thank you! #myfirstpr

**Pull request merged**
