### PR TITLE
feat: add support for MQTT TLS

### PR DESCRIPTION
**Pull request by konturn**
My use-case involves an MQTT broker that uses TLS to communicate--this PR will make this possible.

### CODE REVIEW

**Comment by jakowenko** [comment]
Thank you for this! I will take a look tonight or tomorrow and get it merged in.

**Comment by jakowenko** [comment]
I'm going to close and reopen to see if I can get the diff to update. Right now it's showing old files from beta branch.

**Comment by jakowenko** [comment]
@konturn were you able to test this? I don't see the options for the files in the docs for the mqtt package that is being used. Just wanted to confirm this is accurate.

https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options

**Comment by konturn** [comment]
> @konturn were you able to test this? I don't see the options for the cert files in the docs for the mqtt package that is being used. Just wanted to confirm this is accurate.
> 
> https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options

I was able to test on my infrastructure and everything works (you can see the relevant config files in my Infrastructure-as-Code repo [here](https://github.com/konturn/homelab/blob/main/docker/double-take/config/config.yml) and [here](https://github.com/konturn/homelab/blob/4a88f18a81382e44367ac2e729112c5a8cd95bb6/docker/docker-compose.yml#L547)). After working with it a bit I realized I didn't need to use client certificates, so my config doesn't specify anything but `mqtt.tls.enabled`.

The docs you linked mention that when MQTT over TLS is used, then the options object is passed through to [tls.connect](http://nodejs.org/api/tls.html#tls_tls_connect_options_callback). I did screw up the names for the `key` and `cert` options though, so I've pushed up a fix for that. Also, since client certificates aren't necessarily required, I dropped the one error message I had in place. After I pushed the fix, I tested the `ca`, `key`, and `cert` locally and everything seems to work.

**Comment by jakowenko** [comment]
@konturn should we support the ability to pass the key and certs as file paths or were you thinking you would just save the full contents of those into the config?

**Comment by konturn** [comment]
@jakowenko would preferably want to pass them as paths and load the data into the vars. I'm seeing now that I'd have to make a further update to allow this, since the tls.connect function takes the file contents. Should I add a function to `fs.util.js` that allows reading from files?

**Comment by jakowenko** [comment]
Hey @konturn, sorry for the delay. I refactored the code slightly and updated it to read in the file with `fs`.

You should be able to pass the path of the cert and key now like this.

```yaml
mqtt:
  host: localhost
  tls:
    cert: ./client.crt
    key: ./client.key
```

**Pull request merged**
