### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Alfiegerner**
Small tweaks to hopefully help other newbies like myself - use default frigate port, and add not on compreface service to use.

Another suggestion would be not using port 3000 as this is the standard grafana port (and I think that it's contention for other apps too) - anything to avoid the small obstacles that can make installing this as easy as possible.  Great app - thanks for you efforts.

### CODE REVIEW

**Comment by jakowenko** [comment]
Thanks for the suggestions! I forgot I changed the Frigate port on my setup, so good call on updating to make it the default.

**Comment by Alfiegerner** [comment]
Yeah good question, 3987 seems pretty clear.

**Comment by jakowenko** [comment]
> Yeah good question, 3987 seems pretty clear.

Where did you come up with that port number? I'd probably like to make it a little easier to remember if possible. `1000-9000`. Or if those common ones are all used maybe doing something like `3001`.

**Comment by Alfiegerner** [comment]
I went down the rabbit hole of looking which ports were used by applications, e.g. for port 3001:

https://www.speedguide.net/port.php?port=3001

As you'd expect more amenable a number is the the more likely apps will be already using it.

Having said that, for what we're looking at here I'm probably over optimizing and 3001 should be fine for HA / frigate / double-take servers.

**Comment by jakowenko** [comment]
Ah that makes sense. Keep in mind the application can really run on any port, it's just the port you bind it to on the host machine you need to make sure isn't being used. So in theory Double Take can continue to run on `3000` within the container, but you can bind that to any port you want on the machine running the container. But I agree trying to find one that isn't used with the common Docker containers is a good idea.

**Pull request merged**
